
import os
import re
import win32com.client
import win32timezone
import pubchempy as pcp
import codecs


def search(dirname):
    flist = os.listdir(dirname)
    for f in flist:
        next = os.path.join(dirname, f)
        if os.path.isdir(next):
            search(next)
        else:
            doFileWork(next)

def doFileWork(filename):
    ext = os.path.splitext(filename)[-1]
    if ext == '.xlsx': print(filename)

    excel = win32com.client.Dispatch("Excel.Application")
    excel.Visible = True
    wb = excel.Workbooks.Open(filename)
    ws = wb.ActiveSheet

    n = input('공시품 관련 데이타를 읽을 행을 입력하세요: ')

    구분 = ws.Cells(n,3).Value
    시험내용 = ws.Cells(n,11).Value
    시료명1 = ws.Cells(n,19).Value
    한글명1 = ws.Cells(n,20).Value
    시료명2 = ws.Cells(n,39).Value
    한글명2 = ws.Cells(n,40).Value
    시료명3 = ws.Cells(n,59).Value
    한글명3 = ws.Cells(n,60).Value
    시험물질 = ws.Cells(n,4).Value
    분석일 = ws.Cells(n,10).Value

    try:
        if 시료명1 == None:
            시료명1IUPAC = ""

        else:
            시료명1CID = pcp.get_compounds(시료명1, 'name')
            시료명1IUPAC = 시료명1CID[0].iupac_name

    except IndexError:
        시료명1IUPAC = ""

    try:
        if 시료명2 == None:
            시료명2IUPAC = ""

        else:
            시료명2CID = pcp.get_compounds(시료명2, 'name')
            시료명2IUPAC = 시료명2CID[0].iupac_name

    except IndexError:
        시료명2IUPAC = ""

    try:
        if 시료명3 == None:
            시료명3IUPAC = ""

        else:
            시료명3CID = pcp.get_compounds(시료명3, 'name')
            시료명3IUPAC = 시료명3CID[0].iupac_name

    except IndexError:
        시료명3IUPAC = ""

    분석기기1 = ws.Cells(n,14).Value
    분석기기2 = ws.Cells(n,15).Value
    분석기기3 = ws.Cells(n,16).Value

    제형코드 = 시험물질[-2:]

    LOTNO = ws.Cells(n,5).Value
    제조년 = '20'+list(re.findall(r"(\d+)", LOTNO)[0])[0]+list(re.findall(r"(\d+)", LOTNO)[0])[1]
    제조월 = list(re.findall(r"(\d+)", LOTNO)[0])[2]+list(re.findall(r"(\d+)", LOTNO)[0])[3]
    제조일 = list(re.findall(r"(\d+)", LOTNO)[0])[4]+list(re.findall(r"(\d+)", LOTNO)[0])[5]

    if 제형코드 == "DT":
        제형분류 = "직접살포정제"
        수량 = "100g"
    else:
        print("보류")

    함량 = re.findall(r"(\d+)", 시험물질)
    함량.extend(["",""])

    함량1 = 함량[0]+'%'

    if 함량[1] == "":
        함량2 = ""
    else:
        함량2 = 함량[1]+'%'

    if 함량[2] == "":
        함량3 = ""
    else:
        함량3 = 함량[2]+'%'

    print ('구분: ', 구분)
    print ('시험내용: ', 시험내용)
    print ('시험물질: ', 시험물질)
    print ('시료명: ', 시료명1, 시료명2, 시료명3, 제형코드)
    print('IUPAC NAME: ',시료명1IUPAC)
    print('IUPAC NAME: ',시료명2IUPAC)
    print('IUPAC NAME: ',시료명3IUPAC)
    print ('한글명: ', 한글명1, 한글명2, 한글명3, 제형분류)
    print ('수량: ', 수량)
    print ('함량: ',함량1, 함량2, 함량3)
    print ('Lot No.: ',LOTNO, ' 제조년월일:', 제조년+'년', 제조월+'월', 제조일+'일')
    print ('분석일: ',분석일.year,'년:',분석일.month,'월',분석일.day,'일')
    print ('해당 폴더에 공시품 파일(c:\works\공시품.xml 을 작성중입니다.')

    f = codecs.open("c:\data automation\공시품.xml", 'w', 'utf-8')

    f.write('<?xml version="1.0"?>\n')
    f.write('<?mso-application progid="Excel.Sheet"?>\n')
    f.write('<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"\n')
    f.write(' xmlns:o="urn:schemas-microsoft-com:office:office"\n')
    f.write(' xmlns:x="urn:schemas-microsoft-com:office:excel"\n')
    f.write(' xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"\n')
    f.write(' xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"\n')
    f.write(' xmlns:html="http://www.w3.org/TR/REC-html40">\n')
    f.write(' <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">\n')
    f.write('  <Author>농업기술연구소</Author>\n')
    f.write('  <LastAuthor>LG PC</LastAuthor>\n')
    f.write('  <LastPrinted>2016-02-04T13:01:49Z</LastPrinted>\n')
    f.write('  <Created>1999-12-11T04:38:33Z</Created>\n')
    f.write('  <LastSaved>2016-02-04T13:02:59Z</LastSaved>\n')
    f.write('  <Version>12.00</Version>\n')
    f.write(' </DocumentProperties>\n')
    f.write(' <CustomDocumentProperties xmlns="urn:schemas-microsoft-com:office:office">\n')
    f.write('  <IVID2F1E1603 dt:dt="string"></IVID2F1E1603>\n')
    f.write('  <IVIDC dt:dt="string"></IVIDC>\n')
    f.write('  <IVID362F13E8 dt:dt="string"></IVID362F13E8>\n')
    f.write('  <IVID3A3618F1 dt:dt="string"></IVID3A3618F1>\n')
    f.write('  <IVID15E41318 dt:dt="string"></IVID15E41318>\n')
    f.write('  <IVID181914D9 dt:dt="string"></IVID181914D9>\n')
    f.write('  <IVID155815FB dt:dt="string"></IVID155815FB>\n')
    f.write('  <IVIDD091BF0 dt:dt="string"></IVIDD091BF0>\n')
    f.write('  <IVID344CCFFC dt:dt="string"></IVID344CCFFC>\n')
    f.write('  <IVID1A7D12ED dt:dt="string"></IVID1A7D12ED>\n')
    f.write('  <IVID1B2115FE dt:dt="string"></IVID1B2115FE>\n')
    f.write('  <IVID35431BD0 dt:dt="string"></IVID35431BD0>\n')
    f.write('  <IVID4637A884 dt:dt="string"></IVID4637A884>\n')
    f.write('  <IVID127C14F5 dt:dt="string"></IVID127C14F5>\n')
    f.write('  <IVID1834F0DD dt:dt="string"></IVID1834F0DD>\n')
    f.write('  <IVID312119E0 dt:dt="string"></IVID312119E0>\n')
    f.write('  <IVID1C5812DA dt:dt="string"></IVID1C5812DA>\n')
    f.write('  <IVID173907ED dt:dt="string"></IVID173907ED>\n')
    f.write('  <IVID1D3F17E2 dt:dt="string"></IVID1D3F17E2>\n')
    f.write('  <IVID13451200 dt:dt="string"></IVID13451200>\n')
    f.write('  <IVID475611CF dt:dt="string"></IVID475611CF>\n')
    f.write('  <IVID302D13DA dt:dt="string"></IVID302D13DA>\n')
    f.write('  <IVIDD5915D9 dt:dt="string"></IVIDD5915D9>\n')
    f.write('  <IVID17F6384A dt:dt="string"></IVID17F6384A>\n')
    f.write('  <IVID3B5A10EA dt:dt="string"></IVID3B5A10EA>\n')
    f.write('  <IVID3D0F16E3 dt:dt="string"></IVID3D0F16E3>\n')
    f.write('  <IVID30260FFC dt:dt="string"></IVID30260FFC>\n')
    f.write('  <IVID2F301BED dt:dt="string"></IVID2F301BED>\n')
    f.write('  <IVID2F1117F5 dt:dt="string"></IVID2F1117F5>\n')
    f.write('  <IVID121617DE dt:dt="string"></IVID121617DE>\n')
    f.write('  <IVID13691AF2 dt:dt="string"></IVID13691AF2>\n')
    f.write('  <IVID1A3B0AF0 dt:dt="string"></IVID1A3B0AF0>\n')
    f.write('  <IVID373F12DB dt:dt="string"></IVID373F12DB>\n')
    f.write('  <IVID274B1CF5 dt:dt="string"></IVID274B1CF5>\n')
    f.write('  <IVID2B4E17FA dt:dt="string"></IVID2B4E17FA>\n')
    f.write('  <IVID253D11EF dt:dt="string"></IVID253D11EF>\n')
    f.write('  <IVID102124BA dt:dt="string"></IVID102124BA>\n')
    f.write('  <IVID3D1509D0 dt:dt="string"></IVID3D1509D0>\n')
    f.write('  <IVID35641901 dt:dt="string"></IVID35641901>\n')
    f.write('  <IVID45E1ED9 dt:dt="string"></IVID45E1ED9>\n')
    f.write('  <IVID324113D1 dt:dt="string"></IVID324113D1>\n')
    f.write('  <IVID1A2D1903 dt:dt="string"></IVID1A2D1903>\n')
    f.write('  <IVID222F6E42 dt:dt="string"></IVID222F6E42>\n')
    f.write('  <IVID137012E9 dt:dt="string"></IVID137012E9>\n')
    f.write('  <IVID3D4D17F3 dt:dt="string"></IVID3D4D17F3>\n')
    f.write('  <IVID2F2214CF dt:dt="string"></IVID2F2214CF>\n')
    f.write('  <IVID212812E2 dt:dt="string"></IVID212812E2>\n')
    f.write('  <IVID174513DF dt:dt="string"></IVID174513DF>\n')
    f.write('  <IVID14481408 dt:dt="string"></IVID14481408>\n')
    f.write('  <IVID2E670A05 dt:dt="string"></IVID2E670A05>\n')
    f.write('  <IVID2A161305 dt:dt="string"></IVID2A161305>\n')
    f.write('  <IVID173E1206 dt:dt="string"></IVID173E1206>\n')
    f.write('  <IVID232310EC dt:dt="string"></IVID232310EC>\n')
    f.write('  <IVID133D1AE5 dt:dt="string"></IVID133D1AE5>\n')
    f.write('  <IVIDF6113D9 dt:dt="string"></IVIDF6113D9>\n')
    f.write('  <IVID362E14DB dt:dt="string"></IVID362E14DB>\n')
    f.write('  <IVID1F6511DB dt:dt="string"></IVID1F6511DB>\n')
    f.write('  <IVID3F1D10E8 dt:dt="string"></IVID3F1D10E8>\n')
    f.write('  <IVID144313EE dt:dt="string"></IVID144313EE>\n')
    f.write('  <IVID272C0FEF dt:dt="string"></IVID272C0FEF>\n')
    f.write('  <IVID240A1504 dt:dt="string"></IVID240A1504>\n')
    f.write('  <IVID2E511106 dt:dt="string"></IVID2E511106>\n')
    f.write('  <IVID2A6D14EB dt:dt="string"></IVID2A6D14EB>\n')
    f.write('  <IVID386F14FA dt:dt="string"></IVID386F14FA>\n')
    f.write('  <IVIDA1B07F3 dt:dt="string"></IVIDA1B07F3>\n')
    f.write('  <IVID2A6715D8 dt:dt="string"></IVID2A6715D8>\n')
    f.write('  <IVID222D19FF dt:dt="string"></IVID222D19FF>\n')
    f.write('  <IVID2D4D15EB dt:dt="string"></IVID2D4D15EB>\n')
    f.write('  <IVID1A3517F4 dt:dt="string"></IVID1A3517F4>\n')
    f.write('  <IVID2B0E1302 dt:dt="string"></IVID2B0E1302>\n')
    f.write('  <IVID332E19D7 dt:dt="string"></IVID332E19D7>\n')
    f.write('  <IVID22261800 dt:dt="string"></IVID22261800>\n')
    f.write('  <IVID325116DE dt:dt="string"></IVID325116DE>\n')
    f.write('  <IVID81113D2 dt:dt="string"></IVID81113D2>\n')
    f.write('  <IVID1D231201 dt:dt="string"></IVID1D231201>\n')
    f.write('  <IVID366A14F0 dt:dt="string"></IVID366A14F0>\n')
    f.write('  <IVID316311F9 dt:dt="string"></IVID316311F9>\n')
    f.write('  <IVIDE0715F1 dt:dt="string"></IVIDE0715F1>\n')
    f.write('  <IVID3B5816EC dt:dt="string"></IVID3B5816EC>\n')
    f.write('  <IVID351414F8 dt:dt="string"></IVID351414F8>\n')
    f.write('  <IVID2F251AE7 dt:dt="string"></IVID2F251AE7>\n')
    f.write('  <IVID2A5E1D03 dt:dt="string"></IVID2A5E1D03>\n')
    f.write('  <IVID306310DF dt:dt="string"></IVID306310DF>\n')
    f.write('  <IVID266F16CF dt:dt="string"></IVID266F16CF>\n')
    f.write('  <IVID307414D1 dt:dt="string"></IVID307414D1>\n')
    f.write('  <IVID344B1400 dt:dt="string"></IVID344B1400>\n')
    f.write('  <IVID135B1DF5 dt:dt="string"></IVID135B1DF5>\n')
    f.write('  <IVID1A3716D3 dt:dt="string"></IVID1A3716D3>\n')
    f.write('  <IVIDD1916DB dt:dt="string"></IVIDD1916DB>\n')
    f.write('  <IVID11431AF1 dt:dt="string"></IVID11431AF1>\n')
    f.write('  <IVID1B2C19F3 dt:dt="string"></IVID1B2C19F3>\n')
    f.write('  <IVIDD5E0FE6 dt:dt="string"></IVIDD5E0FE6>\n')
    f.write('  <IVID162D1605 dt:dt="string"></IVID162D1605>\n')
    f.write('  <IVID28741007 dt:dt="string"></IVID28741007>\n')
    f.write('  <IVID2A3614FA dt:dt="string"></IVID2A3614FA>\n')
    f.write('  <IVID15231CDF dt:dt="string"></IVID15231CDF>\n')
    f.write('  <IVID322814F3 dt:dt="string"></IVID322814F3>\n')
    f.write('  <IVID2F6C14EF dt:dt="string"></IVID2F6C14EF>\n')
    f.write('  <IVID252617FB dt:dt="string"></IVID252617FB>\n')
    f.write('  <IVIDA0D1BD8 dt:dt="string"></IVIDA0D1BD8>\n')
    f.write('  <IVID3E4418F8 dt:dt="string"></IVID3E4418F8>\n')
    f.write('  <IVID18751B08 dt:dt="string"></IVID18751B08>\n')
    f.write('  <IVID86E1200 dt:dt="string"></IVID86E1200>\n')
    f.write('  <IVID157115F8 dt:dt="string"></IVID157115F8>\n')
    f.write('  <IVID1ACF422B dt:dt="string"></IVID1ACF422B>\n')
    f.write('  <IVID406811FD dt:dt="string"></IVID406811FD>\n')
    f.write('  <IVID376316F1 dt:dt="string"></IVID376316F1>\n')
    f.write(' </CustomDocumentProperties>\n')
    f.write(' <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel">\n')
    f.write('  <WindowHeight>8448</WindowHeight>\n')
    f.write('  <WindowWidth>7368</WindowWidth>\n')
    f.write('  <WindowTopX>5988</WindowTopX>\n')
    f.write('  <WindowTopY>-12</WindowTopY>\n')
    f.write('  <TabRatio>844</TabRatio>\n')
    f.write('  <ProtectStructure>False</ProtectStructure>\n')
    f.write('  <ProtectWindows>False</ProtectWindows>\n')
    f.write(' </ExcelWorkbook>\n')
    f.write(' <Styles>\n')
    f.write('  <Style ss:ID="Default" ss:Name="Normal">\n')
    f.write('   <Alignment ss:Vertical="Bottom"/>\n')
    f.write('   <Borders/>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern"/>\n')
    f.write('   <Interior/>\n')
    f.write('   <NumberFormat/>\n')
    f.write('   <Protection/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="m68882184">\n')
    f.write('   <Alignment ss:Horizontal="Left" ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="11"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="m68882204">\n')
    f.write('   <Alignment ss:Horizontal="Left" ss:Vertical="Center" ss:WrapText="1"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="11"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s66">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s67">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s70">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s72">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s73">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s74">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('   <Borders/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s75">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s77">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s100">\n')
    f.write('   <Alignment ss:Horizontal="Left" ss:Vertical="Center"/>\n')
    f.write('   <Borders/>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="12"/>\n')
    f.write('   <Interior/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s147">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('   <NumberFormat ss:Format="0.00000_ "/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s179">\n')
    f.write('   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>\n')
    f.write('   <Borders/>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="14"\n')
    f.write('    ss:Bold="1"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s180">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="12"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s181">\n')
    f.write('   <Alignment ss:Horizontal="Left" ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="11"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s182">\n')
    f.write('   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="11"/>\n')
    f.write('   <Interior/>\n')
    f.write('   <NumberFormat ss:Format="Long Date"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s183">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('   <Borders/>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="14"\n')
    f.write('    ss:Bold="1"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s184">\n')
    f.write('   <Alignment ss:Horizontal="Right" ss:Vertical="Center"/>\n')
    f.write('   <Borders/>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="16"\n')
    f.write('    ss:Bold="1"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s185">\n')
    f.write('   <Alignment ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="14"\n')
    f.write('    ss:Bold="1"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s186">\n')
    f.write('   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="14"\n')
    f.write('    ss:Bold="1"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s550">\n')
    f.write('   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="20"\n')
    f.write('    ss:Bold="1"/>\n')
    f.write('  </Style>\n')
    f.write('  <Style ss:ID="s557">\n')
    f.write('   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>\n')
    f.write('   <Borders>\n')
    f.write('    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('    <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>\n')
    f.write('   </Borders>\n')
    f.write('   <Font ss:FontName="돋움" x:CharSet="129" x:Family="Modern" ss:Size="11"/>\n')
    f.write('  </Style>\n')
    f.write(' </Styles>\n')
    f.write(' <Worksheet ss:Name="공시품">\n')
    f.write('  <Table ss:ExpandedColumnCount="10" ss:ExpandedRowCount="17" x:FullColumns="1"\n')
    f.write('   x:FullRows="1" ss:StyleID="s66" ss:DefaultColumnWidth="45"\n')
    f.write('   ss:DefaultRowHeight="13.2">\n')
    f.write('   <Column ss:StyleID="s66" ss:AutoFitWidth="0" ss:Width="11.399999999999999"\n')
    f.write('    ss:Span="1"/>\n')
    f.write('   <Column ss:Index="3" ss:StyleID="s66" ss:AutoFitWidth="0" ss:Width="110.4"/>\n')
    f.write('   <Column ss:StyleID="s66" ss:AutoFitWidth="0" ss:Width="119.4"/>\n')
    f.write('   <Column ss:StyleID="s66" ss:AutoFitWidth="0" ss:Width="95.399999999999991"\n')
    f.write('    ss:Span="1"/>\n')
    f.write('   <Column ss:Index="7" ss:StyleID="s66" ss:AutoFitWidth="0" ss:Width="9.6"/>\n')
    f.write('   <Row ss:Height="15.600000000000001">\n')
    f.write('    <Cell ss:Index="3" ss:StyleID="s180"><Data ss:Type="String">[별지 제1호서식]</Data></Cell>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:Height="25.8">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s70"/>\n')
    f.write('    <Cell ss:MergeAcross="3" ss:StyleID="s550"><Data ss:Type="String">공 시 품 표 시</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s72"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row>\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:AutoFitHeight="0" ss:Height="30">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s181"><Data ss:Type="String">공시품의명칭</Data></Cell>\n')
    f.write('    <Cell ss:MergeAcross="2" ss:StyleID="m68882184"><Data ss:Type="String"> ')

    f.write(한글명1)

    if 한글명2 == None:
        f.write('')
    else:
        f.write('.'+한글명2)

    if 한글명3 == None:
        f.write('')
    else:
        f.write('.'+한글명3)

    f.write(' ')
    f.write(제형분류)
    f.write('</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:AutoFitHeight="0" ss:Height="47.25">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s181"><Data ss:Type="String">주성분 함유량</Data></Cell>\n')
    f.write('    <Cell ss:MergeAcross="2" ss:StyleID="m68882204"><Data ss:Type="String"> ')
    f.write(시료명1)
    f.write('&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;- ')
    f.write(함량1)
    f.write('&#10; ')

    if 시료명2 == None:
        f.write('')
    else:
        f.write(시료명2)

    if 시료명2 == None:
        f.write('')
    else:
        f.write('&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;- ')

    f.write(함량2)

    f.write('&#10; ')

    if 시료명3 == None:
        f.write('')
    else:
        f.write(시료명3)

    if 시료명3 == None:
        f.write('')
    else:
        f.write('&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;- ')

    f.write(함량3)

    f.write('</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:AutoFitHeight="0" ss:Height="21.75">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s181"><Data ss:Type="String">제조자 및 제조장소</Data></Cell>\n')
    f.write('    <Cell ss:MergeAcross="2" ss:StyleID="s557"><Data ss:Type="String">동부팜한농(주) 동부기술원</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:AutoFitHeight="0" ss:Height="21.75">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s181"><Data ss:Type="String">발취자 및 발취장소</Data></Cell>\n')
    f.write('    <Cell ss:MergeAcross="2" ss:StyleID="s557"><Data ss:Type="String">동부팜한농(주) 동부기술원</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:AutoFitHeight="0" ss:Height="21.75">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s181"><Data ss:Type="String">제조 년월일</Data></Cell>\n')
    f.write('    <Cell ss:MergeAcross="2" ss:StyleID="s182"><Data ss:Type="DateTime">')
    f.write(제조년)
    f.write('-')
    f.write(제조월)
    f.write('-')
    f.write(제조일)
    f.write('T00:00:00.000')
    f.write('</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:AutoFitHeight="0" ss:Height="21.75">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s181"><Data ss:Type="String">제조 일년번호</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s182"><Data ss:Type="String">')
    f.write(LOTNO)
    f.write('</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s182"><Data ss:Type="String">수량</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s182"><Data ss:Type="String">')
    f.write(수량)
    f.write('</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:AutoFitHeight="0" ss:Height="21.75">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s181"><Data ss:Type="String">발취 년월일</Data></Cell>\n')
    f.write('    <Cell ss:MergeAcross="2" ss:StyleID="s182"><Data ss:Type="DateTime">')
    f.write(제조년)
    f.write('-')
    f.write(제조월)
    f.write('-')
    f.write(제조일)
    f.write('T00:00:00.000')
    f.write('</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row>\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row>\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('    <Cell ss:Index="10" ss:StyleID="s147"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:Height="15.600000000000001">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s100"><Data ss:Type="String">신청인 주소 : 서울특별시 강남구 테헤란로 432 동부금융센타 19층</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:Height="15.600000000000001">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s100"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row>\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s74"/>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:Height="20.399999999999999">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s73"/>\n')
    f.write('    <Cell ss:StyleID="s183"/>\n')
    f.write('    <Cell ss:StyleID="s183"/>\n')
    f.write('    <Cell ss:StyleID="s179"/>\n')
    f.write('    <Cell ss:StyleID="s184"><Data ss:Type="String">동부팜한농 주식회사 대표이사       (인)</Data></Cell>\n')
    f.write('    <Cell ss:StyleID="s75"/>\n')
    f.write('   </Row>\n')
    f.write('   <Row ss:Height="17.399999999999999">\n')
    f.write('    <Cell ss:Index="2" ss:StyleID="s67"/>\n')
    f.write('    <Cell ss:StyleID="s185"/>\n')
    f.write('    <Cell ss:StyleID="s185"/>\n')
    f.write('    <Cell ss:StyleID="s186"/>\n')
    f.write('    <Cell ss:StyleID="s186"/>\n')
    f.write('    <Cell ss:StyleID="s77"/>\n')
    f.write('   </Row>\n')
    f.write('  </Table>\n')
    f.write('  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">\n')
    f.write('   <PageSetup>\n')
    f.write('    <Layout x:CenterHorizontal="1"/>\n')
    f.write('    <Header x:Margin="0.31496062992125984"/>\n')
    f.write('    <Footer x:Margin="0.31496062992125984"/>\n')
    f.write('    <PageMargins x:Bottom="0.74803149606299213" x:Left="0" x:Right="0"\n')
    f.write('     x:Top="0.74803149606299213"/>\n')
    f.write('   </PageSetup>\n')
    f.write('   <Print>\n')
    f.write('    <ValidPrinterInfo/>\n')
    f.write('    <PaperSizeIndex>9</PaperSizeIndex>\n')
    f.write('    <HorizontalResolution>600</HorizontalResolution>\n')
    f.write('    <VerticalResolution>600</VerticalResolution>\n')
    f.write('   </Print>\n')
    f.write('   <Selected/>\n')
    f.write('   <Panes>\n')
    f.write('    <Pane>\n')
    f.write('     <Number>3</Number>\n')
    f.write('     <ActiveRow>4</ActiveRow>\n')
    f.write('     <ActiveCol>8</ActiveCol>\n')
    f.write('    </Pane>\n')
    f.write('   </Panes>\n')
    f.write('   <ProtectObjects>False</ProtectObjects>\n')
    f.write('   <ProtectScenarios>False</ProtectScenarios>\n')
    f.write('  </WorksheetOptions>\n')
    f.write(' </Worksheet>\n')
    f.write('</Workbook>\n')

    excel.Quit()

search("c:/data automation")